AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'coverage/*'
    - 'features/step_definitions/web_steps.rb'
    - 'features/support/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/WordArray:
  EnforcedStyle: brackets

Style/NumericLiterals:
  Enabled: false

Metrics/MethodLength:
  Max: 20